#!/usr/bin/env bash
# Configure Nginx to run as nginx user
/usr/sbin/nginx -s stop
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx /var/log/nginx
/usr/sbin/nginx
